(()=>{'use strict';if(window.miraiAnalytics)return;
const KEY='mirai_analytics_choice_v1',SK='mirai_analytics_session_v1';let choice='no',state=null,pageSent=false,disabled=false;
const page=(location.pathname.split('/').pop()||'index.html').replace(/\.html$/,''),allowed=['index','about','affiliates','contact','faq','guide','peptide','policies','portal','privacy','research-use-only','stack','terms'];
try{choice=localStorage.getItem(KEY);state=JSON.parse(sessionStorage.getItem(SK)||'null');}catch{disabled=true;}
const respected=navigator.globalPrivacyControl===true||navigator.doNotTrack==='1';
function send(kind,compound=null){if(disabled||respected||choice!=='yes'||!allowed.includes(page))return;try{
if(!state||Date.now()-state.last>1800000)state={id:crypto.randomUUID(),last:Date.now()};state.last=Date.now();sessionStorage.setItem(SK,JSON.stringify(state));
fetch('https://qymwaujpaxbmeohcmueh.supabase.co/rest/v1/rpc/mirai_track',{method:'POST',headers:{'Content-Type':'application/json',apikey:'sb_publishable_sIt2p8INDif9VfTb4F81YQ_yEoGr5fE'},body:JSON.stringify({p_id:crypto.randomUUID(),p_session:state.id,p_kind:kind,p_page:page,p_compound:compound}),keepalive:true}).catch(()=>{});
}catch{}}
function start(){if(!pageSent&&choice==='yes'&&!respected){pageSent=true;send('page_view');if(page==='peptide'){const id=new URLSearchParams(location.search).get('id');if(id&&/^[a-z0-9-]{1,60}$/.test(id))send('product_view',id);}}}
function settings(){document.getElementById('mirai-analytics-choice')?.remove();const box=document.createElement('aside');box.id='mirai-analytics-choice';box.setAttribute('aria-label','Optional analytics');box.style.cssText='position:fixed;bottom:16px;left:16px;right:16px;max-width:480px;z-index:900;background:#fff;color:#12283a;padding:20px;border:1px solid #ccd8e1;border-radius:14px;box-shadow:0 4px 22px #0003;font:14px/1.5 system-ui';box.innerHTML='<strong>Optional website analytics</strong><p>Allow anonymous session and product-interest measurements to help improve the site? No names, contact details, payment information or full URLs are included. Ordering works either way.</p><p><a href="./privacy.html">Privacy policy</a></p>';
for(const [label,val] of [['Allow analytics','yes'],['No thanks','no']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='margin:8px 8px 0 0;padding:10px 14px;border:1px solid #52697b;border-radius:8px;background:white;color:#12283a;cursor:pointer';b.onclick=()=>{choice=val;try{localStorage.setItem(KEY,val);if(val==='no'){sessionStorage.removeItem(SK);state=null;}}catch{}box.remove();start();};box.appendChild(b);}if(respected){box.append(' Your browser privacy signal is respected; optional tracking stays off.');}document.body.appendChild(box);}
window.miraiAnalytics={track:send,disable:()=>{disabled=true;},settings};
function init(){const b=document.createElement('button');b.type='button';b.textContent='Analytics preferences';b.style.cssText='display:block;margin:18px auto;padding:8px 12px;font:13px system-ui;background:transparent;color:inherit;border:1px solid #99aabb;border-radius:6px';b.onclick=settings;document.body.appendChild(b);if(!choice&&!respected&&!disabled)settings();start();}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
